const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, 'data.ts');
let content = fs.readFileSync(dataPath, 'utf8');

const newReviews = [
  { id: "r_entre557_1", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2023", author: "Jonathan Goodin", content: "Really enjoyed this class. Lance is a great professor and although you learn a lot in the course, it is very low stress. Had it over zoom so didn't get the full experience, but builds on what you learned in the Core Finance class. Good class if you interested in valuation, IPOs, and term sheets as you go into depth with these subjects." },
  { id: "r_entre557_2", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2024", author: "Liza Sankar-gorton", content: "Love this class, Lance is engaging and his goal is really just for you to learn, it's laid back but he'll push you to really understand the concepts. highly highly recommend even if finance isn't your jam." },
  { id: "r_entre557_3", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2025", author: "Reed Hawkins", content: "Focuses on entrepreneurial financial decision-making from startup to VC funding. Part I covers survival finance (performance, planning, valuation); Part II focuses on venture capital terms, IPOs, and fund structure. Heavy use of real-world cases. Lance is a polarizing but passionate instructor; come prepared and ready for cold calls. I liked the course and would overall recommend it." },
  { id: "r_entre557_4", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2025", author: "Nick Stuart", content: "Great class, Lance is fantastic in the classroom. I felt like there was a disconnect with the assignments, which are challenging. But the classroom experience is one of the best and Lance makes it fun and engaging. I learned a lot." },
  { id: "r_entre557_5", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2023", author: "Jennifer Cole", content: "Lance is THE man and Entre Finance is the greatest of his course offerings. You're not getting the Foster education without taking at least one Lance class during your time at Foster. Truly, he's a stand out professor. He's dedicated to student learning and classroom inclusivity. As for this class in particular, there is no final, no midterms. There are 4 deliverables that took me around 4-6 hours each. Grading was fair, if tougher for this class than his others. My recomendation, take this class AFTER Problems in business finance, if you can. After taking this course, you'll have a strong understanding of what motivates founders, how to dig into venture capital term sheets, and a stronger, grounded knowledge of all things Core Finance. Entre Finance and Problems in Biz finance, in my mind, should be core classes at Foster. Do yourself a favor and take these classes with Lance. From someone who entered Foster with ZERO finance background, this was a challenging but fun course." },
  { id: "r_entre557_6", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2019", author: "Alex Moore", content: "Not strictly an ENTRE class. I would recommend to anyone interested in Finance classes at all. Lance has engaging lectures and a great system for tackling cases. Favorite class I have taken at Foster. Even though I took it during the summer I was excited about going to class every night" },
  { id: "r_entre557_7", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2019", author: "Breanne Jesionowski", content: "I STRUGGLED through core finance with Mark. Lance's class helped me connect the dots. A lot of it is a continuation of core, paired with core strategy learnings as well. Lance is engaging and provides lots of examples throughout the class. From a workload perspective, its a case per week, and you better do them because he will cold call on anyone." },
  { id: "r_entre557_8", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2019", author: "Eric Simpson", content: "Like others have said, I STRUGGLED through core finance with Mark. For me, Lance's class was really refreshing. A bit of crossover with core, but through a different lens. For me, core finance was very left brained and Entre finance was more right brain focused. As Joe mentioned, this class really should be a required course for all students at the end of year 2. It perfectly combines finance and strategy with bits of accounting." },
  { id: "r_entre557_9", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2019", author: "Joe Nekrasz", content: "This is the best class at Foster even if you don't like finance. It should be a capstone course for our MBA. I'd probably vote for Lance if he ran for President." },
  { id: "r_entre557_10", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2020", author: "Alyssa Lachner", content: "Highly recommend this class. It pulls all the info together from all the other classes so it all makes sense together. Really it should be Core class." },
  { id: "r_entre557_11", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2020", author: "Heidi Hunt", content: "Best class I've taken. Very challenging and requires significant work and preparation but the material is highly useful and Lance Young is one of the most engaging professors at Foster." },
  { id: "r_entre557_12", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2020", author: "Jackson Taylor", content: "Others have already said it as well as I could say it. This should be a required elective. Lance is fantastic. Take it!" },
  { id: "r_entre557_13", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2020", author: "Phalynn Spence", content: "I really loved this class. Easily a top 5 class for me. Echoing what a lot of people have said - it was a difficult but rewarding class. I thought Lance provided really great frameworks to think about how finance is connected to operations, and a tangible way to think about business from a numbers perspective. He also goes over start up financing really well." },
  { id: "r_entre557_14", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2024", author: "Alex Macintosh", content: "Highly recommend - first half will be a great reinforcement of important core finance principles that are especially relevant to an entreprenuer, the second half is all about deciphering term sheets. As in other Lance classes, it's 4 cases that will take as much time as you want to put into them. I took this as an evening class (despite being FT) and really liked having 3.5hrs at once of Lance per week (caveat is that I love Lance's style so take my enthusiasm with that in mind!)" },
  { id: "r_entre557_15", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2025", author: "Sam Hodge", content: "Fall 2024. Lance is a great professor and makes the 3 hours fly by. Great course, you will learn a lot and you will make a lot of mistakes on cases but have a growth mindset. The beginning will start out like the M&A class (I took this class right after taking M&A so the first half of the class felt useless to me). The second half was fun and interesting, going over the term sheets and seeing how startups choose between IPOs or business sales - pretty eye opening how hard it is to get a big payoff when working at a startup." },
  { id: "r_entre557_16", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2025", author: "Unknown", content: "Good class overall and I did learn a lot. No midterm, no final. However, each class was quite intense as he cold-called everyone throughout the class, none stop. There were 4 assignments, each worth 25% and they are very challenging to someone without a finance background. Even though he claimed these assignments would be graded \"based on effort\", he will evaluate how you apply the material/concept he taught in class. Expect to spend 5-8 hours on each assignment. Highly recommend to have a group of people you like to take this class together as you can discuss the assignments as a group." },
  { id: "r_entre557_17", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2026", author: "Peter Schock", content: "Really enjoyed this one. Lance's classroom style was fairly polarizing amongst our class in 502, but he shines with this course and material. Discussions are lively, and Lance brings a lot of nuance to venture capital topics that are often misunderstood. A must for aspiring founders." },
  { id: "r_entre557_18", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2023", author: "Bridget Burkett", content: "I won't belabor what others have said. it's a good class. I do want to share that there are two sections of class. The first half is very similar to Core Finance with Lance but diving deeper into those diagrams. The second half is completely different and focuses on how to read and understand Term Sheets for securing financing for startups. It's helpful to understand how that works but I was definitely surprised by the sharp left turn half way through." },
  { id: "r_entre557_19", courseId: "ENTRE/FIN 557", professor: "Lance Young", year: "2023", author: "Niall Curley", content: "As others have said, this class is it. Lance's baby. He created this class, is in the process of writing a textbook on entre finance (which doesn't really exist), and really knows everything about the subject. If you're even slightly interested in finance, or working at a startup, this class is essential. I was pleasantly surprised at how much you go over things like assessing the competitive environment, doing a market analysis of sorts, and coming up with a strategy. Realizing there is a reason behind every price, and that tells you something. The material in this class is useful for other things beyond just startups, although that is the main focus. Quite an amazing course and I think it should be core in all honesty." },
  { id: "r_mgmt509_1", courseId: "MGMT 509", professor: "Charles Hill", year: "2019", author: "Eric Simpson", content: "Hands down my favorite class I've taken. Charles has a similar teaching style to David Sirmon in Core Strategy. The class is high energy and very engaging. I learned more about macro-economics and the global business externalities in 4 weeks than in all of core macro. The only downside (if it can be considered a downside) is there is only 1 graded element of the class, a final exam. The final took less than 2 hours, take home, open book, and was heavily curved similar to how Ed Rice curved Micro Economics" },
  { id: "r_mgmt509_2", courseId: "MGMT 509", professor: "Charles Hill", year: "2020", author: "Emily Engel", content: "Could not agree more with Eric Simpson! Charles has a similar teaching style to David Sirmon in Core Strategy (but better). The class is high energy and very engaging. I learned more about macro-economics and the global business externalities in 5 weeks than in all of core macro. Such an incredible course and I wish I could take a whole quarter with him." },
  { id: "r_mgmt509_3", courseId: "MGMT 509", professor: "Charles Hill", year: "2020", author: "Farid Gardashov", content: "I agree with Emily and Eric! This has been the most engaging and interesting class I have taken at Foster so far! I love the professor and his teaching style! You should definitely take this class next spring! I wish it was a full 4 credit class!" },
  { id: "r_mgmt509_4", courseId: "MGMT 509", professor: "Charles Hill", year: "2022", author: "Anthony Chang", content: "I took this class online and overall... enjoyed it. Charles is a wonderfully warm instructor and has a lot of great insight. I'd imagine that this class would be fantastic in person; online it was solid. Expect lots of lively discussion and participation." },
  { id: "r_mgmt509_5", courseId: "MGMT 509", professor: "Kevin Steensma", year: "2023", author: "Ayush Garg", content: "(2 credit course) This course is great for anyone interested in understanding how big multi-national corporations take tough decisions that span borders. Very engaging and high interactive classes with challenging content and mostly more questions than answers. But all of this delivered with ease by Prof Kevin Steensma. At the end of the class, you may not have a lot frameworks to start putting into every case competition out there but you'd start appreciating the cultural intricacies that actually matter in a globalized world. Not too much course load with a single big paper on one case and smaller survey-based or short answer-based assignments for rest of the cases (1-2 cases per week, avg 1.5 cases)." },
  { id: "r_mgmt509_6", courseId: "MGMT 509", professor: "Kevin Steensma", year: "2023", author: "Marshall Yin", content: "I took this class during the summer quarter (when it was still remote). Great course. Engaging. Thoughtful, and not really a lecture. Instead, students are encouraged to sit in the shoes of other cultures, business practices, and experience the nuance of international business. This course is required if you are planning to obtain the global business certificate. If you do not have experience in an international setting via your work or school, this is a great introduction" },
  { id: "r_mgmt509_7", courseId: "MGMT 509", professor: "Kevin Steensma", year: "2024", author: "Sibyl Knopp", content: "I really enjoyed this one! You learn how to bring products into global markets, and the trade, legal, and moral issues around it. It was a moderate amount of work. While I dont think I learned anything that would help me in my current job (program mangement, healthcare), I do feel much more competent talking about these issues and reading the WSJ. I'd take this again!" },
  { id: "r_mgmt509_8", courseId: "MGMT 509", professor: "Kevin Steensma", year: "2024", author: "Tong Yuan Douville", content: "I really liked this class. One of the few opportunities you get at Foster to questions the 1st principle assumptions we make ahout business, capitalism, and globalization. Agree with sibyl that it helps you understand the news and politics. Professor is super chill. I like his personality but I wouldn't say he's an exceptional professor. Pretty straightforward lecturing. A lot of reading, but you don't have to do it all" },
  { id: "r_mgmt509_9", courseId: "MGMT 509", professor: "Kevin Steensma", year: "2025", author: "Chinmayee Shenvi", content: "This course with Professor Kevin Steensma is a fascinating dive into how big companies make tough decisions across different countries. It's all about real-life cases, covering everything from cultural differences to how businesses enter new markets. The classes are interactive and engaging, with lots of discussion. While you won't come out with a ton of new frameworks, you'll definitely learn to see the world of global business in a new light. The workload is manageable, with readings and a few assignments, making it a good choice if you need an international credit. Overall, it's a solid course for understanding how global companies operate." },
  { id: "r_mgmt509_10", courseId: "MGMT 509", professor: "Kevin Steensma", year: "2025", author: "Jennifer Goertz", content: "I was hoping to get more out of this class. It felt like the professor was lecturing off the top of his head. You dive straight into cases in the second class and I wish we would have gotten more of a foundational understanding first. Overall I would say its an average lift with readings for each class, a handful of discussion posts, one case brief, and a take home final. Fine to get an international requirement out of the way, but that's about it." },
  { id: "r_mgmt509_11", courseId: "MGMT 509", professor: "Kevin Steensma", year: "2025", author: "Madison Meredith", content: "I had high hopes, but I wouldn't reccomend this class. It is all about reading and discussing cases. It is a lot of reading, but not so much work you feel overwhelmed by any means. If you need an international requirement it is a fine 2 unit, but the course isn't very well organized and you leave questioning what exactly you were supposed to learn from the class." },
  { id: "r_mgmt509_12", courseId: "MGMT 509", professor: "Kevin Steensma", year: "2025", author: "Nick Stuart", content: "I wouldn't recommend this class. Professor just lectures at you mostly. No discussion between students. There was one simulation that was interesting and engaging...but then nothing else. If you aren't on the professors agenda, you won't get much." },
  { id: "r_mktg568_1", courseId: "MKTG 568", professor: "Shirsho Biswas", year: "2020", author: "Matt Goeppele-Parrish", content: "While the content of this class is interesting, be prepared to be thrown in the deep end on assignments. In class, the professor generally tends to go through concepts very quickly. In fact, during one class, he managed to go through 100 slides in 2.5 hours. Additionally, the class is very R software heavy at the beginning. I would highly recommend taking OPMGT 565 (Business Analytics: Tools for Big Data) before taking this class, especially if you do not have experience with R. The second half of the course is better because the focus of the class changes more towards in-depth discussions about different pricing strategies and he slows down a bit." },
  { id: "r_mktg568_2", courseId: "MKTG 568", professor: "Shiro Biswas", year: "2024", author: "Alec Elgood", content: "Shiro seems to have toned down amount of R significantly from prior years. The remaining concepts felt detailed, but not overly technical. The class sessions though are quite dry, and I wouldn't recommend the class unless you are very interested in pricing." },
  { id: "r_mktg568_3", courseId: "MKTG 568", professor: "Shirsho Biswas", year: "2024", author: "Kanika Prakash", content: "Great class in terms of content and assignemnts. Professor tries to make it as interesting as possible. Very little R taught but the final exam is R heavy" },
  { id: "r_mktg568_4", courseId: "MKTG 568", professor: "Shirsho Biswas", year: "2025", author: "Madison Meredith", content: "This is more of a class for Masters of Data Science than MBA students, so you will be the content structured in a way that is very unuseful in the real world (even the professor says so!) The class is generally an easy lift other than 5 homework assignments that are all group and a take home final. All in all, I wouldn't reccomend." }
];

const reviewsEndIndex = content.lastIndexOf('];');
if (reviewsEndIndex !== -1) {
  const existingReviewsText = content.substring(0, reviewsEndIndex);
  const newReviewsText = newReviews.map(r => JSON.stringify(r, null, 2)).join(',\n  ') + '\n';
  
  const needsComma = existingReviewsText.trim().endsWith('}') || existingReviewsText.trim().endsWith(']') || existingReviewsText.trim().endsWith('"');
  
  const updatedContent = existingReviewsText + (needsComma ? ',\n  ' : '\n  ') + newReviewsText + content.substring(reviewsEndIndex);
  
  fs.writeFileSync(dataPath, updatedContent, 'utf8');
  console.log('Added ' + newReviews.length + ' reviews.');
} else {
  console.log('Could not find reviews array.');
}
